### ISSUE TITLE
Label destination does not exist

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Script-Disassembler#1]
`Exception in thread "main" java.lang.RuntimeException: Couldn't find label destination PTR_384_0
	at org.legendofdragoon.scripting.Compiler.findLabelAddress(Compiler.java:53)
	at org.legendofdragoon.scripting.Compiler.compile(Compiler.java:24)
	at org.legendofdragoon.scripting.launch.Compile.main(Compile.java:40)
`

Happens when compiling DRGN21/36/9 (Seles chest)
Relative pointer PTR_384_0 does not point to anything, so probably decompilation issue rather than compilation?

**Comment by LordMonoxide** [comment]
Closed in 5b3f59c
