### ISSUE TITLE
Lexer labels.get() returns null

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Script-Disassembler#2]
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.legendofdragoon.scripting.Lexer.lex(Lexer.java:100)
	at org.legendofdragoon.scripting.launch.Compile.compile(Compile.java:47)
	at org.legendofdragoon.scripting.launch.Compile.main(Compile.java:63)
```

Test file: DRGN1/338

**Comment by LordMonoxide** [comment]
Fixed in d986882
